Save duplicate after m2o fields updated
tj-django/django-clone pull request #633
Opened 2022-09-07 10:16 UTC by Akollek

**The problem**

It seems that when copying a many to one relationship a duplicate of the other object is created, but the foreign key change on the original object isn't saved. This evaded being caught by tests since the unsaved object was used for comparison.

**The solution**

Save the object again after coping all foreign keys.

2022-09-07 10:18 UTC, Akollek commented
Hey @jackton1 , came across this bug while using django-clone, let me know what you think of the fix

2022-09-09 07:15 UTC, jackton1 requested changes

2022-09-09 07:15 UTC, jackton1 commented on model_clone/tests/test_clone_mixin.py
> +        edition_clone.refresh_from_db()
Can we make a similar change to all test methods prior to checking the expected state of the new object?

2022-09-09 15:57 UTC, jackton1 commented
@all-contributors please add @Akollek for code bug test

2022-09-09 15:59 UTC, merged

2022-09-09 16:00 UTC, jackton1 commented
> Hey @jackton1 , came across this bug while using django-clone, let me know what you think of the fix

LGTM, Thanks for updating the test